### ISSUE TITLE
Getting error after installing package?

### ISSUE THREAD

**Issue by tony** [celery/case#1]
Hi, thank you so much for this library.  You have exactly the decorators a lot of projects need abstracted out!

I'm experiencing a weird issue trying to incorporate case on a project that already has its unittest infrastructure set up.

This is python 2.7 on FreeBSD 11-CURRENT and OS X.  I don't need to alter code to get the error, only need to install case.

For reference, the codebase ref I'm on https://github.com/tony/tmuxp/tree/af322806c55682473f412342f0c3a900561049d5.

I install case:

```
❯ pip install case
Collecting case
  Using cached case-1.1.4-py2.py3-none-any.whl
Collecting mock>=2.0 (from case)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting nose>=1.3.7 (from case)
  Using cached nose-1.3.7-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.7 in ./.venv/lib/python2.7/site-packages (from case)
Collecting unittest2>=0.5.1 (from case)
  Using cached unittest2-1.1.0-py2.py3-none-any.whl
Collecting six (from case)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0->case)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0->case)
  Using cached pbr-1.9.1-py2.py3-none-any.whl
Collecting traceback2 (from unittest2>=0.5.1->case)
  Using cached traceback2-1.4.0-py2.py3-none-any.whl
Collecting argparse (from unittest2>=0.5.1->case)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting linecache2 (from traceback2->unittest2>=0.5.1->case)
  Using cached linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: funcsigs, pbr, six, mock, nose, linecache2, traceback2, argparse, unittest2, case
Successfully installed argparse-1.4.0 case-1.1.4 funcsigs-1.0.2 linecache2-1.0.0 mock-2.0.0 nose-1.3.7 pbr-1.9.1 six-1.10.0 traceback2-1.4.0 unittest2-1.1.0
```

I run the (test runner)[https://github.com/tony/tmuxp/blob/af322806c55682473f412342f0c3a900561049d5/run-tests.py]:

```
❯ make watch_test
if command -v entr > /dev/null; then find . -type f -not -path '*/\.*' | grep -i '.*[.]py' | entr -c make test; else make test; echo "\nInstall entr(1) to automatically run tests on file change.\n See http://entrproject.org/"; fi
./run-tests.py
Traceback (most recent call last):
  File "/usr/home/x/work/python/tmuxp/tmuxp/testsuite/__init__.py", line 236, in main
    unittest.main(testLoader=BetterLoader(), defaultTest='suite')
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 89, in __init__
    self.parseArgs(argv)
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 135, in parseArgs
    self.createTests()
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 142, in createTests
    self.module)
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/loader.py", line 245, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/home/x/work/python/tmuxp/tmuxp/testsuite/__init__.py", line 211, in loadTestsFromName
    raise LookupError('could not find test case for "%s"' % name)
LookupError: could not find test case for "s"
*** Error code 1

Stop.
make[1]: stopped in /usr/home/x/work/python/tmuxp
./run-tests.py
Traceback (most recent call last):
  File "/usr/home/x/work/python/tmuxp/tmuxp/testsuite/__init__.py", line 236, in main
    unittest.main(testLoader=BetterLoader(), defaultTest='suite')
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 89, in __init__
    self.parseArgs(argv)
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 135, in parseArgs
    self.createTests()
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 142, in createTests
    self.module)
  File "/usr/home/x/work/python/tmuxp/.venv/lib/python2.7/site-packages/unittest2/loader.py", line 245, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/home/x/work/python/tmuxp/tmuxp/testsuite/__init__.py", line 211, in loadTestsFromName
    raise LookupError('could not find test case for "%s"' % name)
LookupError: could not find test case for "s"
*** Error code 1

Stop.
make[1]: stopped in /usr/home/x/work/python/tmuxp
```

And bump into an issue when looking up test cases.

https://github.com/tony/tmuxp/blob/af322806c55682473f412342f0c3a900561049d5/tmuxp/testsuite/__init__.py#L211

To recreate (tried on a second machine):

```
pip install --user virtualenv  # if virtualenv not installed
git clone https://github.com/tony/tmuxp
cd tmuxp
git checkout 44d37d2
virtualenv .venv
. .venv/bin/activate
pip install -e .
./run-tests.py  # assure it runs, may fail time-sensitive tests
pip install case
./run-tests.py
```

Second example:

```
❯ ./run-tests.py
Traceback (most recent call last):
  File "/Users/me/study/tmuxp/tmuxp/testsuite/__init__.py", line 239, in main
    unittest.main(testLoader=BetterLoader(), defaultTest='suite')
  File "/Users/me/study/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 89, in __init__
    self.parseArgs(argv)
  File "/Users/me/study/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 135, in parseArgs
    self.createTests()
  File "/Users/me/study/tmuxp/.venv/lib/python2.7/site-packages/unittest2/main.py", line 142, in createTests
    self.module)
  File "/Users/me/study/tmuxp/.venv/lib/python2.7/site-packages/unittest2/loader.py", line 245, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/me/study/tmuxp/tmuxp/testsuite/__init__.py", line 214, in loadTestsFromName
    raise LookupError('could not find test case for "%s"' % name)
LookupError: could not find test case for "s"
```

**Comment by tony** [comment]
Ok, dug deeper.

Here are some notes just for posterity (in case someone bumps into same error)

I can run `python setup.py test` and invoke tests normally, however, `run-tests.py` is getting pulled in as a test.

repl @ https://github.com/tony/tmuxp/blob/af32280/tmuxp/testsuite/__init__.py#L210

```
❯ ./run-tests.py
>>> print(name, module)
s <module '__main__' from './run-tests.py'>
```

``` diff
diff --git a/tmuxp/testsuite/__init__.py b/tmuxp/testsuite/__init__.py
index 351a0d0..d25e0ef 100644
--- a/tmuxp/testsuite/__init__.py
+++ b/tmuxp/testsuite/__init__.py
@@ -205,9 +205,13 @@ class BetterLoader(unittest.TestLoader):
                testname.endswith('.' + name) or \
                ('.' + name + '.') in testname or \
                testname.startswith(name + '.'):
+
                 all_tests.append(testcase)

         if not all_tests:
+            from ptpython.repl import embed
+            embed(globals(), locals(), vi_mode=False, history_filename=None)
+
             raise LookupError('could not find test case for "%s"' % name)

         if len(all_tests) == 1:
```

Here's the issue, why would installing argparse-1.4.0 case-1.1.4 funcsigs-1.0.2 linecache2-1.0.0 mock-2.0.0 nose-1.3.7 pbr-1.9.1 six-1.10.0 traceback2-1.4.0 unittest2-1.1.0 end up making code that works ok now break.

**Comment by tony** [comment]
It seems that installing `unittest2` it the culprit.

Shouldn't `unittest2` be obsolete with python 2.7? I think its just a backport of 2.7's unittest for earlier python versions.

When I move unittest2 to only install with `requirements/py26.txt` (required in setup.py for < 2.7) I am able to use the module successfully.  I made a PR for it

If I'm missing anything let me know, you are god of testing compared to me :P

**Comment by ask** [comment]
As mentioned in the pull request, I'm not sure if Python2.7 unittest is up to date with all changes in unittest2.  I will have to investigate.

I'm so happy you like the project :)
These are a bunch of tools that I have been copy pasting between my projects for a long time, and it's been a pain to keep them up to date, along with general testing requirements so I decided to keep it all in a reusable package.

I haven't been able to write the desperately missing README for this project yet. so I'm glad you found it and could tell it was useful :)

**Comment by tony** [comment]
It was my fault:

I wrapped `import unittest2` in a try-catch, not a `sys.version_info` check. `unittest2` was only installed setup.py if the version was under 2.7.

Since case installed `unittest2` as a dependency, the behavior in python 2.7's test searching changed.

> These are a bunch of tools that I have been copy pasting between my projects for a long time,

Same here. The duplication going in goes too far. I was led here via github.com/search. A certain python library had a nice test decorator but was AGPLv3.

The other thing is I stick to plain-old unittest on things ATM. Maybe pytest or nose is the way but I want it to play out, I don't want to introduce specialized behavior and 2 yrs later end up having to provide life support to a lib that's unmaintained.

It's good to have mute. I'm also looking into the logging decorators more deeply.

lemmi close this and double check some #2 things
